from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# 研究团队状态
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # 多头对话历史
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # 空头对话历史
    history: Annotated[str, "Conversation history"]  # 对话历史
    current_response: Annotated[str, "Latest response"]  # 最新回复
    judge_decision: Annotated[str, "Final judge decision"]  # 最终裁决
    count: Annotated[int, "Length of the current conversation"]  # 对话长度


# 风险管理团队状态
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # 对话历史
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # 对话历史
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # 对话历史
    history: Annotated[str, "Conversation history"]  # 对话历史
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # 最新回复
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # 最新回复
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # 最新回复
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # 对话长度


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # 研究阶段
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # 研究团队讨论阶段
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # 风险管理团队讨论阶段
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
